### ISSUE TITLE
TODO eventually

### ISSUE THREAD

**Issue by crabdancing** [alxpettit/nixpak-flatpak-wrapper#3]
- [x] fix being an 'alternate service'
- Maybe a less stupid name?
  - lol never
- [ ] allow `nixpak-flatpak-wrapper` to be installed without `flatpak`.
  - add dummy flatpak wrapped binary?
- [ ] per-user configuration. This is pretty import for Proper (TM) home-manager modules to integrate with nixpak-flatpak-wrapper. I myself was wanting to do this just today with my personal Firefox module.

**Comment by crabdancing** [comment]
per-user config could be handled with [merge-rs](https://git.sr.ht/~ireas/merge-rs). High-level codegen for merge strats is a little overkill, but will be very future-proof. Can then have standard XDG config files like `~/.config/nixpak-flatpak-wrapper/config.toml` and then layer that config on top of `/etc/nixpak-flatpak-wrapper.toml`. Then use [home-manager's xdg.configFile](https://mynixos.com/home-manager/options/xdg.configFile.%3Cname%3E) option in the homeManagerModule, and we should be golden. :3
